- name: install essential packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - duplicity
  notify: update updatedb

- name: sync duplicity script
  copy:
    src: duplicity/duplicity-backup.sh
    dest: "{{ duplicity_config_dest }}"

- name: sync duplicity global config
  template:
    src: server.conf
    dest: "{{ duplicity_config_dest }}"

- name: check if site config exists
  local_action: stat path={{ inventory_dir }}/files/duplicity/{{ inventory_hostname }}.txt
  register: site_config
  tags: debug

- name: site config warning
  debug:
    msg: |
      Custom site config does not exists! please create your own config in
        {{ inventory_dir }}/files/duplicity/{{ inventory_hostname }}.txt
  when: not site_config.stat.exists
  tags: debug

- name: sync duplicity site config
  copy:
    src: duplicity/{{ inventory_hostname }}.txt
    dest: "{{ duplicity_config_dest }}"
  when: site_config.stat.exists
  tags: debug

- name: create cron
  cron:
    name: duplicity
    minute: 0
    hour: 6
    weekday: 1
    job: "bash {{ duplicity_config_dest }}/duplicity-backup.sh -c '{{ duplicity_config_dest }}/server.conf' -b"
